# Generated by Django 4.1 on 2022-10-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Critico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Crítico')),
                ('c_id', models.IntegerField(verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('critico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.critico', verbose_name='Crítico')),
            ],
        ),
    ]
