# Generated by Django 4.1 on 2022-10-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_critico_data_de_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critico',
            name='data_de_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
