# Generated by Django 4.1 on 2022-11-28 00:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('genero', models.CharField(max_length=20, verbose_name='Genêro')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('critica', models.CharField(max_length=250, verbose_name='Critica')),
                ('data_de_criacao', models.DateTimeField(default=datetime.datetime(2022, 11, 27, 21, 12, 23, 954401))),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudo.filme')),
            ],
        ),
    ]
